consumes:
- application/json
definitions:
  WriteEndpointRequest:
    properties:
      endpoint_id:
        format: int64
        type: integer
        x-go-name: EndpointID
      node_id:
        format: int64
        type: integer
        x-go-name: NodeID
      up:
        format: int64
        type: integer
        x-go-name: Up
    type: object
    x-go-package: github.com/TechMinerApps/upmaster/router/api/v1/status
  WriteEndpointResponse:
    properties:
      endpoint_id:
        format: int64
        type: integer
        x-go-name: EndpointID
      node_id:
        format: int64
        type: integer
        x-go-name: NodeID
      up:
        format: int64
        type: integer
        x-go-name: Up
    type: object
    x-go-package: github.com/TechMinerApps/upmaster/router/api/v1/status
info:
  description: Documentation of upmaster api
paths:
  /status:
    post:
      description: write endpoints status
      operationId: WriteEndpointStatus
      parameters:
      - in: body
        name: Body
        schema:
          items:
            $ref: '#/definitions/WriteEndpointRequest'
          type: array
      responses:
        "200":
          $ref: '#/responses/WriteEndpointStatus'
        "400":
          $ref: '#/responses/BadRequestError'
      tags:
      - Status
produces:
- application/json
responses:
  BadRequestError:
    description: ""
    headers:
      error:
        type: string
  WriteEndpointStatus:
    description: ""
    headers:
      Body: {}
    schema:
      $ref: '#/definitions/WriteEndpointResponse'
schemes:
- http
- https
swagger: "2.0"
