consumes:
- application/json
definitions:
  WriteEndpointRequest:
    properties:
      endpoint_id:
        format: int64
        type: integer
        x-go-name: EndpointID
      node_id:
        format: int64
        type: integer
        x-go-name: NodeID
      up:
        format: int64
        type: integer
        x-go-name: Up
    type: object
    x-go-package: github.com/TechMinerApps/upmaster/router/api/v1/status
  WriteEndpointResponse:
    properties:
      endpoint_id:
        format: int64
        type: integer
        x-go-name: EndpointID
      node_id:
        format: int64
        type: integer
        x-go-name: NodeID
      up:
        format: int64
        type: integer
        x-go-name: Up
    type: object
    x-go-package: github.com/TechMinerApps/upmaster/router/api/v1/status
info:
  description: Documentation of upmaster api
paths:
  /auth/login:
    post:
      description: login with username/email and password
      operationId: LoginCredencials
      parameters:
      - in: body
        name: email
        schema:
          type: string
        x-go-name: Email
      - in: query
        name: username
        type: string
        x-go-name: Username
      - in: query
        name: password
        type: string
        x-go-name: Password
      responses:
        "200":
          $ref: '#/responses/AuthLoginResponse'
        "401":
          description: ""
      tags:
      - Login
  /auth/logout:
    delete:
      description: logout user
      operationId: Logout
      responses:
        "204":
          description: ""
  /auth/reset:
    post:
      description: send reset token to email
      operationId: ResetTokenRequest
      parameters:
      - in: query
        name: email
        type: string
        x-go-name: Email
      responses:
        "204":
          description: ""
        "500":
          description: ""
      tags:
      - SendResetToken
    put:
      description: reset password of curresponding user of the token
      operationId: ResetPasswordRequest
      parameters:
      - in: query
        name: token
        type: string
        x-go-name: Token
      responses:
        "204":
          description: ""
        "404":
          description: ""
      tags:
      - ResetPassword
  /status:
    post:
      description: write endpoints status
      operationId: WriteEndpointStatus
      parameters:
      - in: body
        name: Body
        schema:
          items:
            $ref: '#/definitions/WriteEndpointRequest'
          type: array
      responses:
        "200":
          $ref: '#/responses/WriteEndpointStatus'
        "400":
          $ref: '#/responses/BadRequestError'
      tags:
      - Status
produces:
- application/json
responses:
  AuthLoginResponse:
    description: ""
    headers:
      access_token:
        type: string
      refresh_token:
        type: string
  BadRequestError:
    description: ""
    headers:
      error:
        type: string
  WriteEndpointStatus:
    description: ""
    headers:
      Body: {}
    schema:
      $ref: '#/definitions/WriteEndpointResponse'
schemes:
- http
- https
swagger: "2.0"
